// <auto-generated />
using System;
using EmployeeLeaveManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeLeaveManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401095703_AddedHolidays")]
    partial class AddedHolidays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeLeaveManagement.Models.Employee", b =>
                {
                    b.Property<string>("AssociateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("AssociateId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeLeaveManagement.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Republic Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Republic Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Republic Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Republic Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Republic Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "May Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "May Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "May Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "May Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "May Day",
                            Type = "National"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Gandhi Jayanti",
                            Type = "National"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Gandhi Jayanti",
                            Type = "National"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Gandhi Jayanti",
                            Type = "National"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Gandhi Jayanti",
                            Type = "National"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Gandhi Jayanti",
                            Type = "National"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Christmas",
                            Type = "National"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Christmas",
                            Type = "National"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Christmas",
                            Type = "National"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Christmas",
                            Type = "National"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Christmas",
                            Type = "National"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "New Year",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "New Year",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "New Year",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Pongal/Sankranti",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Pongal/Sankranti",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Pongal/Sankranti",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Holi",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Doljatra",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Ugadi",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Ugadi",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Ramzan",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Ramzan",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Ramzan",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Ramzan",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Ramzan",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Tamil New Year",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Bengali New Year",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Telangana Formation",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Ganesh Chaturthi",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Ganesh Chaturthi",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Ganesh Chaturthi",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "VijayaDasami",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "VijayaDasami",
                            Type = "Regional"
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2026, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Durga Puja",
                            Type = "Regional"
                        });
                });

            modelBuilder.Entity("EmployeeLeaveManagement.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbsenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssociateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("EmployeeLeaveManagement.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Pune"
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Hyderabad"
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Chennai"
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Kolkata"
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Bangalore"
                        });
                });

            modelBuilder.Entity("EmployeeLeaveManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Associate"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Senior Associate"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("EmployeeLeaveManagement.Models.Employee", b =>
                {
                    b.HasOne("EmployeeLeaveManagement.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeLeaveManagement.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EmployeeLeaveManagement.Models.Holiday", b =>
                {
                    b.HasOne("EmployeeLeaveManagement.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("EmployeeLeaveManagement.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
